dubbo:
  application:
    name: goods
  registry:
    protocol: zookeeper
    address: zookeeper://linux:2181
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 20881
spring:
  datasource:
    url: jdbc:mysql://linux:3306/shopping?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #默认使用myisam存储引擎,一条sql一个事务
    hibernate:
      ddl-auto: none
    open-in-view: true #关闭懒加载
