dubbo:
  registry:
    address: zookeeper://linux:2181
    protocol: zookeeper
  protocol:
    port: 20882
    name: dubbo
  monitor:
    protocol: zookeeper
  application:
    name: order
spring:
  rabbitmq:
    port: 5672
    host: linux
    listener:
      direct:
        acknowledge-mode:  manual
      simple:
        acknowledge-mode: manual
    username: guest
    password: guest
    publisher-confirms: true
  datasource:
    url: jdbc:mysql://linux:3306/shopping?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #默认使用myisam存储引擎,一条sql一个事务