spring:
  application:
    name: shopping-cart
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://linux:3306/shopping?serverTimezone=GMT+8
  rabbitmq:
    port: 5672
    host: localhost
    listener:
      direct:
        acknowledge-mode:  manual
    username: guest
    password: guest
dubbo:
#  注册中心协议
  registry:
    protocol: zookeeper
    address:  zookeeper://linux:2181
#  rpc通信协议
  protocol:
    port: 20883
    name: dubbo
  monitor:
    protocol: registry