server:
  port: 80
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
  cache:
    type: redis
  redis:
    host: linux
    database: 0
    port: 6379
  datasource:
    url: jdbc:mysql://linux:3306/shopping?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: linux
    port: 5672
    username: guest
    password: guest
    publisher-confirms: false  #生产者确认
    publisher-returns: true    #生产者消息返回(未路由的消息)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
dubbo:
  application:
    name: main
  registry:
    protocol: zookeeper
    address: zookeeper://linux:2181
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 20880
jwt:
  secret: vicyor
  expiration: 7200000  #2小时